# Generated by Django 4.2.5 on 2023-09-19 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_category', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=300)),
                ('location', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('salary', models.FloatField()),
                ('create_at', models.DateField(auto_now_add=True)),
                ('deadline', models.DateField()),
                ('no_of_vacancy', models.IntegerField()),
                ('job_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webApp.category')),
                ('job_types', models.ManyToManyField(blank=True, to='webApp.type')),
            ],
        ),
    ]
